### ISSUE TITLE
[BUG] 看不了b站主播

### ISSUE THREAD

**Issue by CHDKBL** [xiaoyaocz/dart_simple_live#489]
### 非重复的Issue

- [X] 已确认没有相似的Issue

### BUG内容

看不了b站主播

### 重现步骤

```plain text
随便点一个都是这样
```

### 截图或视频

![image](https://github.com/user-attachments/assets/bb02ce57-6351-47bf-aaa8-87d903211a71)

### 日志

直播平台：哔哩哔哩
房间号：13308358
错误信息：
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("room_info")
----------------
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      BiliBiliSite.getRoomDetail (package:simple_live_core/src/bilibili_site.dart:227)
<asynchronous suspension>
#3      LiveRoomController.loadData (package:simple_live_app/modules/live_room/live_room_controller.dart:281)
<asynchronous suspension>

### 版本号

1.6.5

### 使用版本

正式版(Releases)

### 运行平台

Windows

### 操作系统信息

win10

### 设备信息

pc

**Comment by eason27** [comment]
一样

**Comment by xiaoyaocz** [comment]
下载开发版：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/10264492965

**Comment by npcXxX** [comment]
> 下载开发版：https://github.com/xiaoyaocz/dart_simple_live/actions/runs/10264492965

开发版只在任务管理器里看到有启动前台直接没有显示，不超过两秒就崩溃了

**Comment by yizhucaodeyuanjing** [comment]
同上，a13无法观看任何b站直播，
直播平台：哔哩哔哩

房间号：5050
错误信息：
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("room_info")
----------------
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      BiliBiliSite.getRoomDetail (package:simple_live_core/src/bilibili_site.dart:227)
<asynchronous suspension>
#3      LiveRoomController.loadData (package:simple_live_app/modules/live_room/live_room_controller.dart:281)
<asynchronous suspension>

**Comment by yegetables** [comment]
希望更新release,方便用scoop升级

**Comment by S7K3333** [comment]
一样

**Comment by JZSTAR01** [comment]
抖音也有相同问题，主播是在播的，关注了也不显示在播，打开直播间是相同的错误页面

**Comment by Icecream-2018** [comment]
还特别有意思，白天 b 站都是正常，一到晚上，就出现这个问题

**Comment by QIMIYI** [comment]
一样

**Comment by QIMIYI** [comment]
安卓端也一样

**Comment by zxk2099** [comment]
win +1

**Comment by eason27** [comment]
又不行了

**Comment by thouser8** [comment]
这个问题再次出现

**Comment by dongbao66** [comment]
@xiaoyaocz  b站又不行了

**Comment by include-nan** [comment]
> @xiaoyaocz b站又不行了

换回 release 正式版就可以了

**Comment by dongbao66** [comment]
> > @xiaoyaocz b站又不行了
> 
> 换回 release 正式版就可以了

不是换到正式版就好了，现在测试版也好了，不知道突然抽啥风还是怎么了

**Comment by eason27** [comment]
来回抽风

**Comment by laphang5** [comment]
正式版也不行了

**Comment by xiaoyaocz** [comment]
已知晓，有空就会修，不用一直回复
